### ISSUE TITLE
Make it compatible with GS 40 (minimize to new default dock)

### ISSUE THREAD

**Issue by luca-viggiani** [hermes83/compiz-alike-magic-lamp-effect#6]
In GNOME 40 the new dock at the bottom has been introduced makin dash to dock or similar extension useless.
But when I minimize a window it goes on the top left corner rather than in the GS40 dock at the bottom (using the lates in gnome shell site)

**Comment by hermes83** [comment]
The gnome 40 dock is only visible in the dashboard. The extension works with any dash outside the dashboard.
Tested with plank, no problems are encountered
