### ISSUE TITLE
minimizing to the dock GNOME 40

### ISSUE THREAD

**Issue by MetotoSakamoto** [hermes83/compiz-alike-magic-lamp-effect#7]
In vanilla gnome 40, when a window is minimized, the effect goes to activities in top left corner not into the dock on the bottom

**Comment by a1ad** [comment]
yes please, no its strange to use.

**Comment by hermes83** [comment]
should be fixed on [gnome extension portal](https://extensions.gnome.org/extension/3740/compiz-alike-magic-lamp-effect/?c=102913) and soon will be pushed on github
